version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - ml_network

  redis:
    image: "redis:latest"
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ml_network

networks:
  ml_network:
    driver: bridge
